### ISSUE TITLE
Android 12 crash

### ISSUE THREAD

**Issue by HlebMaliborski** [HMS-Core/hms-push-clientdemo-android#11]
Hi! In our app we have dependency: com.huawei.hms:base:6.1.0.302 and use HuaweiApiAvailability class.

As result of calling this function PendingIntent getErrPendingIntent(Context var1, ConnectionResult var2) we have exception:

Process: com.netcetera.tpmw.ndb.app.preview, PID: 10355
java.lang.IllegalArgumentException: com...preview: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
at android.app.PendingIntent.getActivity(PendingIntent.java:444)
at android.app.PendingIntent.getActivity(PendingIntent.java:408)
at com.huawei.hms.api.b.getErrPendingIntent(HuaweiApiAvailabilityImpl.java:10)
at com.huawei.hms.common.internal.BaseHmsClient.resolution(BaseHmsClient.java:3)
at com.huawei.hms.common.internal.BaseHmsClient.checkAvailabilityAndConnect(BaseHmsClient.java:34)
at com.huawei.hms.common.internal.BaseHmsClient.connect(BaseHmsClient.java:1)
at com.huawei.hms.common.internal.HuaweiApiManager$ConnectionManager.connect(HuaweiApiManager.java:21)
at com.huawei.hms.common.internal.HuaweiApiManager$ConnectionManager.sendRequest(HuaweiApiManager.java:24)
at com.huawei.hms.common.internal.HuaweiApiManager.connectAndSendRequest(HuaweiApiManager.java:8)
at com.huawei.hms.common.internal.HuaweiApiManager.handleMessage(HuaweiApiManager.java:7)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)

Question: are you planning to update PendingIntens with new flag for Android 12?

**Comment by Mike-mei** [comment]
Thank you for your feedback, the R&D team confirms that a fixed version will be released at the end of September. Please use the latest version for testing by that time. Thanks.

See : https://stackoverflow.com/a/69232813/13329100

**Comment by HlebMaliborski** [comment]
@Mike-mei , thanks for response. What the latest version of com.huawei.hms:base?

**Comment by HlebMaliborski** [comment]
Hi @Mike-mei , thanks for response! Do you have exact date when new release will be deployed? Today is 30 of September but there is no new version.

Thanks.

**Comment by Mike-mei** [comment]
It's still under development, we will notice you when the new version released.

**Comment by emakar** [comment]
Well, 2022 and issue is still present

**Comment by Mike-mei** [comment]
> Well, 2022 and issue is still present

You can update the push SDK to 6.3.0.300 version, android 12 adaptation issues have been solved in this version, please try again.
<img width="683" alt="05BF8E0A-5451-4839-AF61-4F132CC57F66" src="https://user-images.githubusercontent.com/63704034/148315204-bcace5e3-5528-4de6-aac9-f07f13d57bf9.png">
.

**Comment by emakar** [comment]
Thanks, I'll let you know

**Comment by xiaocode337317439** [comment]
> > Well, 2022 and issue is still present
> 
> You can update the push SDK to 6.3.0.300 version, android 12 adaptation issues have been solved in this version, please try again. <img alt="05BF8E0A-5451-4839-AF61-4F132CC57F66" width="683" src="https://user-images.githubusercontent.com/63704034/148315204-bcace5e3-5528-4de6-aac9-f07f13d57bf9.png"> .

还是存在implementation 'com.huawei.hms:push:6.3.0.300'

Installation failed due to: 'Failed to commit install session 796099279 with command cmd package install-commit 796099279. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl796099279.tmp/base.apk (at Binary XML file line #392): cn.jpush.android.service.PluginOppoPushService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'

**Comment by Xuejiao-Shi** [comment]
@xiaocode337317439 您好，从截图看像是您接入的三方平台那边的报错，建议您直接接入华为推送，我们试了6.3.0.300和6.3.0.302，都没有这个问题

**Comment by minkiapps** [comment]
Fixed with PR #15
